version: "3"
services:
  mariadb:
    image: mysql:5.7
    container_name: randpic_db
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
